In [3]:
import numpy as np
import pandas as pd

In [7]:
#1.Create a null vector of size 10 but the fifth value which is 1.
x1 = (np.arange(10) == 4).view(np.uint8)
print(x1)

[0 0 0 0 1 0 0 0 0 0]


In [8]:
#2. Create a vector with values ranging from 10 to 49.
x2 = np.arange(10,50)
print(x2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
x3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


numpy.ndarray

In [13]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
x4 = np.array([1,2,0,0,4,0])
print(np.nonzero(x4))

(array([0, 1, 4], dtype=int64),)


In [17]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
x5 = np.random.randint(1000,size=(10,10))
print(x5)
print('Min value is ',np.min(x5))
print('Max value is ',np.max(x5))

[[563 792 795 242 499 221 473 534 975 189]
 [626 798 407 120 523 961 793 399 538 285]
 [767 896 603 517 578  23 346 447 337 107]
 [435 909 100 934 868 568 474 652 885 405]
 [354 316 947 588 133 356 207 966 896 292]
 [232 299 366 105 186 220 771 967 974 295]
 [473 550  12 637 836 631 509  60 897 346]
 [564   6 213 829 531 254 555 449 879 561]
 [226 117  35 531  91  73 965 169 844  18]
 [856 972 319 709 169 941 153 407 270 728]]
Min value is  6
Max value is  975


In [20]:
#6. Create a random vector of size 30 and find the mean value.
x6=np.random.randint(100,size=30)
print(x6)
print("Mean is : ",np.mean(x6))

[12 76 97 40 71 84 18 87 68 48 23 61 66 96 60 33 89 23 50 10 91 87  7 76
 81 28 51 66 45 68]
Mean is :  57.06666666666667
