1.Extract All Odd Numbers from arr.

In [31]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]

array([1, 3, 5, 7, 9])

2.Replace All Odd Numbers in arr with -1.

In [33]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3.Convert a 1D array to 2D array with 2 rows

In [34]:
arr=np.arange(10)
arr_2D=np.reshape(arr,(2,5))
print(arr_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


4.Stack Arrays a and b vertically.

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
st=np.vstack((a,b))
print(st)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Get all Items between 5 and 10 from a.

In [45]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a>5)*(a<11)]
print(result)

[ 6  9 10]


Create a null vector of size 10 but the fifth value which is 1.

In [46]:
(np.arange(10) == 4).view(np.uint8)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8)

Create a vector with values ranging from 10 to 49.

In [49]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a 10x10 array with random values and find the minimum and maximum values.

In [55]:
x=np.random.randint(1000,size=(10,10))
print(x)
print('Min value is ',np.min(x))
print('Max value is ',np.max(x))

[[743 997 214 543 939  54 532 575 594 510]
 [810 805 140 516 776 181 782 415 851 560]
 [226 605 668 155 824 724 807 263 730 965]
 [ 48 547 496 737 807 723 741 319 149 501]
 [197 396 246  51 671 395 271 487 812 110]
 [587 457 964 252 311 355 841 391 571 403]
 [ 35 515 652 381 121 162 932 926 711 598]
 [235 221 405 294 244 873 339 257 992 443]
 [178 114 131 941  55 452  90 981 309 481]
 [980 738 233 773   8 133  71 796 930 567]]
Min value is  8
Max value is  997


Create a 3*3 matrix and print it's transpose matrix

In [57]:
y=np.random.randint(20,size=(3,3))
print(y)
print(y.transpose())

[[17  6 10]
 [ 9  6  3]
 [ 9  5  7]]
[[17  9  9]
 [ 6  6  5]
 [10  3  7]]


Create two arrays of 2-D and find dot product of it.

In [58]:
m1=np.random.randint(10,size=(2,2))
m2=np.random.randint(50,size=(2,2))
print(np.dot(m1,m2))

[[400 440]
 [323 295]]


Compute the maximum for each row in the given array.

In [61]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
x = np.amax(a, 1)
print('Max in each row are ',x)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
Max in each row are  [9 8 6 3 9]


Select 3rd & 5th row and 3rd & 4th columns

In [63]:
data = np.random.randint(10,100,(5,4))
print(data)

[[71 24 65 81]
 [90 12 29 73]
 [63 37 66 40]
 [58 57 49 48]
 [54 28 74 66]]


Convert below matrix into vector

In [64]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(np.reshape(matrix,-1))

[1 2 3 4 5 6 7 8 9]


The product of two inverse matrix is identical matrix,prove

In [71]:
m = np.array([[2,3],
              [2,4]])
mi=np.linalg.inv(m)
print(mi)
m*mi

[[ 2.  -1.5]
 [-1.   1. ]]


array([[ 4. , -4.5],
       [-2. ,  4. ]])

Create a matrix from a uniform distribution over [0, 1)

In [72]:
u = np.random.uniform(0,1,size=(3,3))
print(u)

[[0.19695569 0.51339886 0.10947407]
 [0.90217668 0.14542386 0.79825258]
 [0.33555027 0.51487497 0.11545178]]
